var fcuapps_view='{"data":['+
        '{"txt":"畢業生專區","url":"nil","item":['+
            '{"txt":"學位服領取歸還查詢","url":"SP8100002"},'+
            '{"txt":"畢業離校流程資訊查詢","url":"SP810003"},'+
            '{"txt":"畢業典禮邀請函通訊資料","url":"SP810004"},'+
            '{"txt":"問卷系統","url":"http://survey.fcu.edu.tw/Login.aspx"}'+
        ']},'+
        '{"txt":"安定就學專區","url":"nil","item":['+
            '{"txt":"就學貸款線上申請","url":"SP4100003"},'+
            '{"txt":"就學優待線上申請","url":"SP4100004"},'+
            '{"txt":"弱勢助學線上申請","url":"SP4100005"},'+
            '{"txt":"生活學習獎助金申請","url":"SP4100006"},'+
            '{"txt":"弱勢學生資格查核結果查詢","url":"https://myfcu.fcu.edu.tw/main/S4101/S410106_feered_query.aspx"},'+
            '{"txt":"校內獎學金","url":"SP4100001"},'+
            '{"txt":"校外獎學金","url":"SP4100002"},'+
            '{"txt":"學習型兼任服務助理實習記錄","url":"SP9000001"}'+
        ']},'+
        '{"txt":"我的逢甲","url":"nil","item":['+
            '{"txt":"學生綜合資料卡","url":"SP1000001"},'+
            '{"txt":"役男兵役狀況調查","url":"SP1100012"},'+
            '{"txt":"Learning Portfolio","url":"https://myfcu.fcu.edu.tw/main/S4208/S4208_learningportfolio_ldap.aspx?ItemParam=Learning"},'+
            '{"txt":"家長資訊系統啟動作業","url":"SP1100009"},'+
            '{"txt":"NID密碼變更","url":"https://netid.fcu.edu.tw/"},'+
            '{"txt":"意見回饋回覆","url":"SP1100011"}'+
        ']},'+
        '{"txt":"學雜費繳費","url":"nil","item":['+
            '{"txt":"繳費查詢","url":"SP1400002"},'+
            '{"txt":"就學貸款線上申請","url":"SP4100003"},'+
            '{"txt":"就學優待線上申請","url":"SP4100004"},'+
            '{"txt":"學雜費繳費證明申請","url":"http://140.134.20.15/stumend/login.do?method=verify"},'+
            '{"txt":"學雜費逾期未繳補單申請請","url":"http://140.134.20.80/w3000/?ctNode=29423&idPath=10530_29417_29418_29423"},'+
            '{"txt":"國際生繳費補印系統","url":"http://140.134.20.80/w3000/PrintEnLogin.aspx"},'+
            '{"txt":"學生會會費繳費申請","url":"SP1400006"},'+
            '{"txt":"學雜費繳費收據","url":"SP1400007"},'+
            '{"txt":"臺灣銀行學雜費入口網","url":"https://school.bot.com.tw/twbank.net/index.aspx?pgid=3"},'+
            '{"txt":"行動e製單","url":"https://service202-sds.fcu.edu.tw/tuition/infologin.aspx?ctNode=42171&idPath=10530_29417"}'+
        ']},'+
        '{"txt":"校園生活與帳務查詢","item":['+
            '{"txt":"體適能查詢及試算","url":"SP3300014"},'+
            '{"txt":"自我健康管理","url":"SP2300001"},'+
            '{"txt":"個人帳務查詢","url":"SP1000002"},'+
            '{"txt":"撥(付)款明細查詢","url":"SP1000003"},'+
            '{"txt":"所得明細查詢","url":"SP1000004"},'+
            '{"txt":"各類所得扣繳暨免扣繳憑單","url":"SP1000005"},'+
            '{"txt":"銀行帳號維護","url":"SP1000006"}'+
        ']},'+
        '{"txt":"課外活動與生活","item":['+
            '{"txt":"請假系統","url":"SP3800001"},'+
            '{"txt":"獎懲記錄查詢","url":"SP4300006"},'+
            '{"txt":"班幹部服務證明","url":"SP4300007"},'+
            '{"txt":"校本部機車證抽籤申請","url":"https://myfcu.fcu.edu.tw/main/S6222/S6222_motorcycle.aspx"},'+
            '{"txt":"二校區機車證抽籤申請","url":"https://myfcu.fcu.edu.tw/main/S6222/S6222_motorcycle_second.aspx"},'+
            '{"txt":"汽車抽籤(博士/進修學士班)","url":"SP9600002"},'+
            '{"txt":"外語文檢定成績登錄","url":"https://myfcu.fcu.edu.tw/main/S7304/S7304_enscore-ins.aspx"},'+
            '{"txt":"證照上傳系統","url":"SP4300002"},'+
            '{"txt":"非社團學習表現成果","url":"SP4300003"},'+
            '{"txt":"社團活動護照","url":"http://infocenter.fcu.edu.tw/assoc/assoc_login.jsp"},'+
            '{"txt":"志工服務時數登錄","url":"http://sdsweb.oit.fcu.edu.tw/stu_VolServ/loginAction.do"}'+
        ']},'+
        '{"txt":"教務資源","item":['+
            '{"txt":"教學助理(TA)請益維護","url":"SP3300011"},'+
            '{"txt":"資電學院主輔學程申請","url":"SP3300011"},'+
            '{"txt":"課制學程申請","url":"SP2100002"},'+
            '{"txt":"學分學程申請","url":"SP2100003"},'+
            '{"txt":"輔系/雙主修申請","url":"SP2100004"},'+
            '{"txt":"學分採計申請","url":"SP2100005"},'+
            '{"txt":"第二專長課程配當查詢","url":"SP2100006"},'+
            '{"txt":"轉系申請及處理進度查詢","url":"SP2100007"},'+
            '{"txt":"抵免學分申請","url":"SP2200001"},'+
            '{"txt":"抵免學分查詢","url":"SP2200002"},'+
            '{"txt":"學習型兼任服務助理媒合","url":"http://140.134.20.15/StuWorkerApply/login.jsp?ctNode=14592&idPath=11551_13675"},'+
            '{"txt":"科技部計畫助理出勤","url":"SP4200005"}'+
        ']},'+
        '{"txt":"課表與學習平台","item":['+
            '{"txt":"我的課表","url":"SP3200004"},'+
            '{"txt":"iLearn 2.0","url":"https://myfcu.fcu.edu.tw/main/S9902/S990203_ilearn2sso_login.aspx"},'+
            '{"txt":"線上學習測驗平台","url":"http://easytest.lib.fcu.edu.tw/"},'+
            '{"txt":"教師與TA請益時間查詢","url":"SP3300003"},'+
            '{"txt":"教學大綱","url":"https://myfcu.fcu.edu.tw/main/S3205/A320501.aspx?appurl=https://service120-sds.fcu.edu.tw/W320104/W320104.aspx@022"},'+
            '{"txt":"考程表","url":"SP3300012"},'+
            '{"txt":"補考及缺考資料查詢","url":"SP3300015"},'+
            '{"txt":"校際課程交流平台","url":"http://www.cttlrc.fcu.edu.tw/Across/SUMA001.aspx"},'+
            '{"txt":"課程檢索系統","url":"https://myfcu.fcu.edu.tw/main/coursesearch.aspx?sso"},'+
            '{"txt":"選課系統","url":"https://course.fcu.edu.tw/"},'+
            '{"txt":"選課地圖","url":"https://myfcu.fcu.edu.tw/main/S3201/S3201_CurriculumMapping_sso.aspx"}'+
        ']},'+
        '{"txt":"成績及修課進度","item":['+
            '{"txt":"服務學習修課進度","url":"SP3300013"},'+
            '{"txt":"操行分數查詢","url":"SP3500004"},'+
            '{"txt":"成績查詢","url":"SP3500001"},'+
            '{"txt":"個人修習記錄查詢","url":"SP3500002"},'+
            '{"txt":"成績暨證明文件申請","url":"https://service120.sds.fcu.edu.tw/w3119/alumnilogin.aspx"},'+
            '{"txt":"形成性評量","url":"SP3600001"},'+
            '{"txt":"學生課程學習回饋表","url":"SP3600003"}'+
        ']},'+
        '{"txt":"住宿專區","item":['+
            '{"txt":"租屋專區","url":"https://rent.housefun.com.tw/school/fcu/searchlist.aspx"},'+
            '{"txt":"住宿點名系統","url":"SP9500005"},'+
            '{"txt":"宿舍抽籤申請","url":"SP9500003"},'+
            '{"txt":"宿舍設備維修業務申請","url":"https://myfcu.fcu.edu.tw/main/S4202/S4202_dormRepairList.aspx"}'+
        ']},'+
        '{"txt":"空間查詢與借用","item":['+
            '{"txt":"教室借用查詢","url":"SP9300001"},'+
            '{"txt":"教室課表查詢","url":"SP9300002"},'+
            '{"txt":"積學堂(人創)空間借用","url":"https://myfcu.fcu.edu.tw/main/S5672/S5672_learningroom.aspx"},'+
            '{"txt":"圖書館空間借用","url":"https://myfcu.fcu.edu.tw/main/S5672/S5672_library.aspx"},'+
            '{"txt":"體育處戶外場地借用","url":"https://myfcu.fcu.edu.tw/main/S5672/S5672_sport.aspx"}'+
        ']},'+
        '{"txt":"學校資源","item":['+
            '{"txt":"Mymail","url":"https://mymail.fcu.edu.tw/"},'+
            '{"txt":"Gomail服務","url":"https://myfcu.fcu.edu.tw/main/S9902/gomail.htm"},'+
            '{"txt":"雲端應用程式(CLOUDAPP)","url":"https://cloudapp2.fcu.edu.tw/"},'+
            '{"txt":"Office365","url":"http://www.o365.fcu.edu.tw/"},'+
            '{"txt":"校園軟體","url":"http://software-bank.fcu.edu.tw/"},'+
            '{"txt":"Sky雲端空間","url":"https://sky.fcu.edu.tw/navigate/"},'+
            '{"txt":"法規查詢","url":"https://apps.fcu.edu.tw/fculaw/Default.aspx?version=stu"},'+
            '{"txt":"校園新聞","url":"SP9400003"},'+
            '{"txt":"座談會公告查詢","url":"SP9400004"},'+
            '{"txt":"書報攤","url":"https://fengchia.sharepoint.com/sites/e-paper/"},'+
            '{"txt":"訪客與活動臨時無線帳號申請","url":"https://wifiguest.fcu.edu.tw/guest/GuestregPage.php?_browser=1"},'+
            '{"txt":"學生信件通告","url":"SP1100010"},'+
            '{"txt":"失物招領","url":"http://www.life.fcu.edu.tw/wSite/lp?ctNode=11025&mp=221101&idPath=11020_11025"}'+
        ']}'+
    ']}';